# Uncomment the next line to define a global platform for your project

platform :ios, '11.0'

target 'GeoTrackKitExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GeoTrackKitExample
  pod 'GeoTrackKit', :subspecs => ['HealthKit', 'SQLite'], :path => '..'

  target 'GeoTrackKitExampleTests' do
    inherit! :search_paths
  end

  target 'WatchExample Extension' do
    platform :watchos, '6.0'
    pod 'GeoTrackKit', :subspecs => ['WatchCore', 'SQLite'], :path => '..'
  end

end
