
fastlane_version "1.83.0"

default_platform :ios

platform :ios do
  scheme = "GeoTrackKitExample"
  workspace = "GeoTrackKitExample/GeoTrackKitExample.xcworkspace"

  desc "Runs all the tests"
  lane :test do
    clear_derived_data
    scan(scheme: scheme, workspace: workspace)
  end

end
